/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Graph3dRouteImport } from './routes/graph3d'
import { Route as IndexRouteImport } from './routes/index'

const Graph3dRoute = Graph3dRouteImport.update({
  id: '/graph3d',
  path: '/graph3d',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph3d': typeof Graph3dRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graph3d': typeof Graph3dRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graph3d': typeof Graph3dRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/graph3d'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/graph3d'
  id: '__root__' | '/' | '/graph3d'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Graph3dRoute: typeof Graph3dRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/graph3d': {
      id: '/graph3d'
      path: '/graph3d'
      fullPath: '/graph3d'
      preLoaderRoute: typeof Graph3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Graph3dRoute: Graph3dRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
